update

diff --git a/config/scripts/waybar/get_weather b/config/scripts/waybar/get_weather
--- a/config/scripts/waybar/get_weather
+++ b/config/scripts/waybar/get_weather
@@ -1,25 +1,24 @@
 #!/usr/bin/env bash
 
 # get_weather.sh
-for i in {1..5}
-do
-    text=$(curl -s "https://wttr.in/$1?format=1")
-    if (echo $text | grep -i "unknown" >/dev/null );then
-      text="$(whoami)"
-    else
-      text="$text"
+for i in {1..5}; do
+  text=$(curl -s "https://wttr.in/$1?format=1")
+  if (echo $text | grep -i "unknown" >/dev/null); then
+    text="$(whoami)"
+  elif (echo $text | grep -i "error" >/dev/null); then
+    text="$(whoami)"
+  else
+    text="$text"
+  fi
+  if [[ $? == 0 ]]; then
+    text=$(echo "$text" | sed -E "s/\s+/ /g")
+    tooltip=$(curl -s "https://wttr.in/$1?format=4")
+    if [[ $? == 0 ]]; then
+      tooltip=$(echo "$tooltip" | sed -E "s/\s+/ /g")
+      echo "{\"text\":\"$text\", \"tooltip\":\"$tooltip\"}"
+      exit
     fi
-    if [[ $? == 0 ]]
-    then
-        text=$(echo "$text" | sed -E "s/\s+/ /g")
-        tooltip=$(curl -s "https://wttr.in/$1?format=4")
-        if [[ $? == 0 ]]
-        then
-            tooltip=$(echo "$tooltip" | sed -E "s/\s+/ /g")
-            echo "{\"text\":\"$text\", \"tooltip\":\"$tooltip\"}"
-            exit
-        fi
-    fi
-    sleep 2
+  fi
+  sleep 2
 done
 echo "{\"text\":\"error\", \"tooltip\":\"error\"}"
